// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmgthlgycfdffskicirq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttZ3RobGd5Y2ZkZmZza2ljaXJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTcxNTQsImV4cCI6MjA2NjA5MzE1NH0.DTIOuJHQw5zdS-8wK8S8vDY6N74owQX_f1TqsCBcbak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);